"""Add new game fields

Revision ID: bf4c11c68b03
Revises: 
Create Date: 2025-01-16 10:37:32.443934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4c11c68b03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('drm_notice', sa.Text(), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('drm_notice')
        batch_op.drop_column('access_type')

    # ### end Alembic commands ###
